version: '3.8'

services:
  web:
    build: .
    ports:
      - "44441:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: happy
      MYSQL_DATABASE: recipe_database
    volumes:
      - db_data:/var/lib/mysql
      - ./recipes.sql:/docker-entrypoint-initdb.d/recipes.sql

volumes:
  db_data:
